/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mastermind_michelland_peron;

/**
 *
 * @author guilh
 */
public class Mastermind_Graphique extends javax.swing.JFrame {

    /**
     * Creates new form Mastermind_Graphique
     */
    public Mastermind_Graphique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_creation_partie4 = new javax.swing.JPanel();
        jLabel_NbEssaisRest4 = new javax.swing.JLabel();
        NbEssaisRest4 = new javax.swing.JTextField();
        btn_start4 = new javax.swing.JButton();
        panneau_creation_partie5 = new javax.swing.JPanel();
        jLabel_NbEssaisRest5 = new javax.swing.JLabel();
        NbEssaisRest5 = new javax.swing.JTextField();
        btn_start5 = new javax.swing.JButton();
        panneau_creation_partie6 = new javax.swing.JPanel();
        jLabel_NbEssaisRest6 = new javax.swing.JLabel();
        NbEssaisRest6 = new javax.swing.JTextField();
        btn_start6 = new javax.swing.JButton();
        panneau_creation_partie7 = new javax.swing.JPanel();
        jLabel_NbEssaisRest7 = new javax.swing.JLabel();
        NbEssaisRest7 = new javax.swing.JTextField();
        btn_start7 = new javax.swing.JButton();
        panneau_creation_partie = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        panneau_creation_partie1 = new javax.swing.JPanel();
        jLabel_NbEssaisRest1 = new javax.swing.JLabel();
        NbEssaisRest1 = new javax.swing.JTextField();
        btn_start1 = new javax.swing.JButton();
        panneau_creation_partie2 = new javax.swing.JPanel();
        jLabel_NbEssaisRest2 = new javax.swing.JLabel();
        NbEssaisRest2 = new javax.swing.JTextField();
        btn_start2 = new javax.swing.JButton();
        panneau_creation_partie3 = new javax.swing.JPanel();
        jLabel_NbEssaisRest3 = new javax.swing.JLabel();
        NbEssaisRest3 = new javax.swing.JTextField();
        btn_start3 = new javax.swing.JButton();
        jLabel_NbEssaisRest8 = new javax.swing.JLabel();
        NbEssaisRest = new javax.swing.JTextField();
        stat_partie = new javax.swing.JPanel();
        jLabel_NbEssaisRest = new javax.swing.JLabel();
        jLabel_NbEssaisRest9 = new javax.swing.JLabel();
        mal_place = new javax.swing.JTextField();
        bien_place = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        panneau_creation_partie4.setBackground(new java.awt.Color(255, 255, 153));
        panneau_creation_partie4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NbEssaisRest4.setText("Nombre d'essais restants :");
        panneau_creation_partie4.add(jLabel_NbEssaisRest4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panneau_creation_partie4.add(NbEssaisRest4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, -1));

        btn_start4.setText("Lancer la partie");
        btn_start4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start4ActionPerformed(evt);
            }
        });
        panneau_creation_partie4.add(btn_start4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        panneau_creation_partie5.setBackground(new java.awt.Color(255, 255, 153));
        panneau_creation_partie5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NbEssaisRest5.setText("Nombre d'essais restants :");
        panneau_creation_partie5.add(jLabel_NbEssaisRest5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panneau_creation_partie5.add(NbEssaisRest5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, -1));

        btn_start5.setText("Lancer la partie");
        btn_start5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start5ActionPerformed(evt);
            }
        });
        panneau_creation_partie5.add(btn_start5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        panneau_creation_partie4.add(panneau_creation_partie5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 230, 120));

        panneau_creation_partie6.setBackground(new java.awt.Color(255, 255, 153));
        panneau_creation_partie6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NbEssaisRest6.setText("Nombre d'essais restants :");
        panneau_creation_partie6.add(jLabel_NbEssaisRest6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panneau_creation_partie6.add(NbEssaisRest6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, -1));

        btn_start6.setText("Lancer la partie");
        btn_start6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start6ActionPerformed(evt);
            }
        });
        panneau_creation_partie6.add(btn_start6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        panneau_creation_partie7.setBackground(new java.awt.Color(255, 255, 153));
        panneau_creation_partie7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NbEssaisRest7.setText("Nombre d'essais restants :");
        panneau_creation_partie7.add(jLabel_NbEssaisRest7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panneau_creation_partie7.add(NbEssaisRest7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, -1));

        btn_start7.setText("Lancer la partie");
        btn_start7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start7ActionPerformed(evt);
            }
        });
        panneau_creation_partie7.add(btn_start7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        panneau_creation_partie6.add(panneau_creation_partie7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 230, 120));

        panneau_creation_partie4.add(panneau_creation_partie6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 230, 120));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panneau_creation_partie.setBackground(new java.awt.Color(0, 51, 51));
        panneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_start.setText("Lancer la partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        panneau_creation_partie1.setBackground(new java.awt.Color(255, 255, 153));
        panneau_creation_partie1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NbEssaisRest1.setText("Nombre d'essais restants :");
        panneau_creation_partie1.add(jLabel_NbEssaisRest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panneau_creation_partie1.add(NbEssaisRest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, -1));

        btn_start1.setText("Lancer la partie");
        btn_start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start1ActionPerformed(evt);
            }
        });
        panneau_creation_partie1.add(btn_start1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        panneau_creation_partie.add(panneau_creation_partie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 230, 120));

        panneau_creation_partie2.setBackground(new java.awt.Color(255, 255, 153));
        panneau_creation_partie2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NbEssaisRest2.setText("Nombre d'essais restants :");
        panneau_creation_partie2.add(jLabel_NbEssaisRest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panneau_creation_partie2.add(NbEssaisRest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, -1));

        btn_start2.setText("Lancer la partie");
        btn_start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start2ActionPerformed(evt);
            }
        });
        panneau_creation_partie2.add(btn_start2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        panneau_creation_partie3.setBackground(new java.awt.Color(255, 255, 153));
        panneau_creation_partie3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NbEssaisRest3.setText("Nombre d'essais restants :");
        panneau_creation_partie3.add(jLabel_NbEssaisRest3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panneau_creation_partie3.add(NbEssaisRest3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, -1));

        btn_start3.setText("Lancer la partie");
        btn_start3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start3ActionPerformed(evt);
            }
        });
        panneau_creation_partie3.add(btn_start3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        panneau_creation_partie2.add(panneau_creation_partie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 230, 120));

        panneau_creation_partie.add(panneau_creation_partie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 230, 120));

        jLabel_NbEssaisRest8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NbEssaisRest8.setText("Nombre d'essais restants :");
        panneau_creation_partie.add(jLabel_NbEssaisRest8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panneau_creation_partie.add(NbEssaisRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, -1));

        stat_partie.setBackground(new java.awt.Color(0, 51, 51));
        stat_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NbEssaisRest.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NbEssaisRest.setText("Pions mal placés :");
        stat_partie.add(jLabel_NbEssaisRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel_NbEssaisRest9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NbEssaisRest9.setText("Pions bien placés :");
        stat_partie.add(jLabel_NbEssaisRest9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        stat_partie.add(mal_place, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 60, -1));

        bien_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bien_placeActionPerformed(evt);
            }
        });
        stat_partie.add(bien_place, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 60, -1));

        jPanel2.setBackground(new java.awt.Color(177, 94, 18));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(stat_partie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panneau_creation_partie, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panneau_creation_partie, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stat_partie, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(319, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        stat_partie.setVisible(true);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_start1ActionPerformed

    private void btn_start2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_start2ActionPerformed

    private void btn_start3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_start3ActionPerformed

    private void btn_start4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_start4ActionPerformed

    private void btn_start5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_start5ActionPerformed

    private void btn_start6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_start6ActionPerformed

    private void btn_start7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_start7ActionPerformed

    private void bien_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bien_placeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bien_placeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mastermind_Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mastermind_Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mastermind_Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mastermind_Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mastermind_Graphique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NbEssaisRest;
    private javax.swing.JTextField NbEssaisRest1;
    private javax.swing.JTextField NbEssaisRest2;
    private javax.swing.JTextField NbEssaisRest3;
    private javax.swing.JTextField NbEssaisRest4;
    private javax.swing.JTextField NbEssaisRest5;
    private javax.swing.JTextField NbEssaisRest6;
    private javax.swing.JTextField NbEssaisRest7;
    private javax.swing.JTextField bien_place;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_start1;
    private javax.swing.JButton btn_start2;
    private javax.swing.JButton btn_start3;
    private javax.swing.JButton btn_start4;
    private javax.swing.JButton btn_start5;
    private javax.swing.JButton btn_start6;
    private javax.swing.JButton btn_start7;
    private javax.swing.JLabel jLabel_NbEssaisRest;
    private javax.swing.JLabel jLabel_NbEssaisRest1;
    private javax.swing.JLabel jLabel_NbEssaisRest2;
    private javax.swing.JLabel jLabel_NbEssaisRest3;
    private javax.swing.JLabel jLabel_NbEssaisRest4;
    private javax.swing.JLabel jLabel_NbEssaisRest5;
    private javax.swing.JLabel jLabel_NbEssaisRest6;
    private javax.swing.JLabel jLabel_NbEssaisRest7;
    private javax.swing.JLabel jLabel_NbEssaisRest8;
    private javax.swing.JLabel jLabel_NbEssaisRest9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mal_place;
    private javax.swing.JPanel panneau_creation_partie;
    private javax.swing.JPanel panneau_creation_partie1;
    private javax.swing.JPanel panneau_creation_partie2;
    private javax.swing.JPanel panneau_creation_partie3;
    private javax.swing.JPanel panneau_creation_partie4;
    private javax.swing.JPanel panneau_creation_partie5;
    private javax.swing.JPanel panneau_creation_partie6;
    private javax.swing.JPanel panneau_creation_partie7;
    private javax.swing.JPanel stat_partie;
    // End of variables declaration//GEN-END:variables
}
